#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScheduleManagementUsingWFA
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ScheduleManagement")]
	public partial class ScheduleManagementDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCaLamViec(CaLamViec instance);
    partial void UpdateCaLamViec(CaLamViec instance);
    partial void DeleteCaLamViec(CaLamViec instance);
    partial void InsertChiTietNhanVien(ChiTietNhanVien instance);
    partial void UpdateChiTietNhanVien(ChiTietNhanVien instance);
    partial void DeleteChiTietNhanVien(ChiTietNhanVien instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    partial void InsertThoiGianLamViec(ThoiGianLamViec instance);
    partial void UpdateThoiGianLamViec(ThoiGianLamViec instance);
    partial void DeleteThoiGianLamViec(ThoiGianLamViec instance);
    partial void InsertViTriLamViec(ViTriLamViec instance);
    partial void UpdateViTriLamViec(ViTriLamViec instance);
    partial void DeleteViTriLamViec(ViTriLamViec instance);
    partial void InsertPhanCongLamViec(PhanCongLamViec instance);
    partial void UpdatePhanCongLamViec(PhanCongLamViec instance);
    partial void DeletePhanCongLamViec(PhanCongLamViec instance);
    #endregion
		
		public ScheduleManagementDataContext() : 
				base(global::ScheduleManagementUsingWFA.Properties.Settings.Default.ScheduleManagementConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ScheduleManagementDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ScheduleManagementDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ScheduleManagementDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ScheduleManagementDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CaLamViec> CaLamViecs
		{
			get
			{
				return this.GetTable<CaLamViec>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietNhanVien> ChiTietNhanViens
		{
			get
			{
				return this.GetTable<ChiTietNhanVien>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<ThoiGianLamViec> ThoiGianLamViecs
		{
			get
			{
				return this.GetTable<ThoiGianLamViec>();
			}
		}
		
		public System.Data.Linq.Table<ViTriLamViec> ViTriLamViecs
		{
			get
			{
				return this.GetTable<ViTriLamViec>();
			}
		}
		
		public System.Data.Linq.Table<PhanCongLamViec> PhanCongLamViecs
		{
			get
			{
				return this.GetTable<PhanCongLamViec>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CaLamViec")]
	public partial class CaLamViec : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Ca;
		
		private EntitySet<PhanCongLamViec> _PhanCongLamViecs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnCaChanging(string value);
    partial void OnCaChanged();
    #endregion
		
		public CaLamViec()
		{
			this._PhanCongLamViecs = new EntitySet<PhanCongLamViec>(new Action<PhanCongLamViec>(this.attach_PhanCongLamViecs), new Action<PhanCongLamViec>(this.detach_PhanCongLamViecs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ca", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string Ca
		{
			get
			{
				return this._Ca;
			}
			set
			{
				if ((this._Ca != value))
				{
					this.OnCaChanging(value);
					this.SendPropertyChanging();
					this._Ca = value;
					this.SendPropertyChanged("Ca");
					this.OnCaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CaLamViec_PhanCongLamViec", Storage="_PhanCongLamViecs", ThisKey="Id", OtherKey="MaCaLV")]
		public EntitySet<PhanCongLamViec> PhanCongLamViecs
		{
			get
			{
				return this._PhanCongLamViecs;
			}
			set
			{
				this._PhanCongLamViecs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhanCongLamViecs(PhanCongLamViec entity)
		{
			this.SendPropertyChanging();
			entity.CaLamViec = this;
		}
		
		private void detach_PhanCongLamViecs(PhanCongLamViec entity)
		{
			this.SendPropertyChanging();
			entity.CaLamViec = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietNhanVien")]
	public partial class ChiTietNhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Mau;
		
		private int _CaLV;
		
		private int _ThuLV;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMauChanging(string value);
    partial void OnMauChanged();
    partial void OnCaLVChanging(int value);
    partial void OnCaLVChanged();
    partial void OnThuLVChanging(int value);
    partial void OnThuLVChanged();
    #endregion
		
		public ChiTietNhanVien()
		{
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mau", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Mau
		{
			get
			{
				return this._Mau;
			}
			set
			{
				if ((this._Mau != value))
				{
					this.OnMauChanging(value);
					this.SendPropertyChanging();
					this._Mau = value;
					this.SendPropertyChanged("Mau");
					this.OnMauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CaLV", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int CaLV
		{
			get
			{
				return this._CaLV;
			}
			set
			{
				if ((this._CaLV != value))
				{
					this.OnCaLVChanging(value);
					this.SendPropertyChanging();
					this._CaLV = value;
					this.SendPropertyChanged("CaLV");
					this.OnCaLVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThuLV", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ThuLV
		{
			get
			{
				return this._ThuLV;
			}
			set
			{
				if ((this._ThuLV != value))
				{
					this.OnThuLVChanging(value);
					this.SendPropertyChanging();
					this._ThuLV = value;
					this.SendPropertyChanged("ThuLV");
					this.OnThuLVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_ChiTietNhanVien", Storage="_NhanVien", ThisKey="Id", OtherKey="Id", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.ChiTietNhanViens.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.ChiTietNhanViens.Add(this);
						this._Id = value.Id;
					}
					else
					{
						this._Id = default(int);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _HoTen;
		
		private int _ThoiGianLV;
		
		private EntitySet<ChiTietNhanVien> _ChiTietNhanViens;
		
		private EntitySet<PhanCongLamViec> _PhanCongLamViecs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnHoTenChanging(string value);
    partial void OnHoTenChanged();
    partial void OnThoiGianLVChanging(int value);
    partial void OnThoiGianLVChanged();
    #endregion
		
		public NhanVien()
		{
			this._ChiTietNhanViens = new EntitySet<ChiTietNhanVien>(new Action<ChiTietNhanVien>(this.attach_ChiTietNhanViens), new Action<ChiTietNhanVien>(this.detach_ChiTietNhanViens));
			this._PhanCongLamViecs = new EntitySet<PhanCongLamViec>(new Action<PhanCongLamViec>(this.attach_PhanCongLamViecs), new Action<PhanCongLamViec>(this.detach_PhanCongLamViecs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string HoTen
		{
			get
			{
				return this._HoTen;
			}
			set
			{
				if ((this._HoTen != value))
				{
					this.OnHoTenChanging(value);
					this.SendPropertyChanging();
					this._HoTen = value;
					this.SendPropertyChanged("HoTen");
					this.OnHoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGianLV", DbType="Int NOT NULL")]
		public int ThoiGianLV
		{
			get
			{
				return this._ThoiGianLV;
			}
			set
			{
				if ((this._ThoiGianLV != value))
				{
					this.OnThoiGianLVChanging(value);
					this.SendPropertyChanging();
					this._ThoiGianLV = value;
					this.SendPropertyChanged("ThoiGianLV");
					this.OnThoiGianLVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_ChiTietNhanVien", Storage="_ChiTietNhanViens", ThisKey="Id", OtherKey="Id")]
		public EntitySet<ChiTietNhanVien> ChiTietNhanViens
		{
			get
			{
				return this._ChiTietNhanViens;
			}
			set
			{
				this._ChiTietNhanViens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_PhanCongLamViec", Storage="_PhanCongLamViecs", ThisKey="Id", OtherKey="MaNV")]
		public EntitySet<PhanCongLamViec> PhanCongLamViecs
		{
			get
			{
				return this._PhanCongLamViecs;
			}
			set
			{
				this._PhanCongLamViecs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietNhanViens(ChiTietNhanVien entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_ChiTietNhanViens(ChiTietNhanVien entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
		
		private void attach_PhanCongLamViecs(PhanCongLamViec entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_PhanCongLamViecs(PhanCongLamViec entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ThoiGianLamViec")]
	public partial class ThoiGianLamViec : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _ThoiGian;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnThoiGianChanging(string value);
    partial void OnThoiGianChanged();
    #endregion
		
		public ThoiGianLamViec()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThoiGian", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string ThoiGian
		{
			get
			{
				return this._ThoiGian;
			}
			set
			{
				if ((this._ThoiGian != value))
				{
					this.OnThoiGianChanging(value);
					this.SendPropertyChanging();
					this._ThoiGian = value;
					this.SendPropertyChanged("ThoiGian");
					this.OnThoiGianChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ViTriLamViec")]
	public partial class ViTriLamViec : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _ViTri;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnViTriChanging(string value);
    partial void OnViTriChanged();
    #endregion
		
		public ViTriLamViec()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ViTri", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string ViTri
		{
			get
			{
				return this._ViTri;
			}
			set
			{
				if ((this._ViTri != value))
				{
					this.OnViTriChanging(value);
					this.SendPropertyChanging();
					this._ViTri = value;
					this.SendPropertyChanged("ViTri");
					this.OnViTriChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhanCongLamViec")]
	public partial class PhanCongLamViec : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaNV;
		
		private int _MaCaLV;
		
		private System.Nullable<int> _MaViTriLV;
		
		private int _ThuLamViec;
		
		private EntityRef<CaLamViec> _CaLamViec;
		
		private EntityRef<NhanVien> _NhanVien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(int value);
    partial void OnMaNVChanged();
    partial void OnMaCaLVChanging(int value);
    partial void OnMaCaLVChanged();
    partial void OnMaViTriLVChanging(System.Nullable<int> value);
    partial void OnMaViTriLVChanged();
    partial void OnThuLamViecChanging(int value);
    partial void OnThuLamViecChanged();
    #endregion
		
		public PhanCongLamViec()
		{
			this._CaLamViec = default(EntityRef<CaLamViec>);
			this._NhanVien = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCaLV", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaCaLV
		{
			get
			{
				return this._MaCaLV;
			}
			set
			{
				if ((this._MaCaLV != value))
				{
					if (this._CaLamViec.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaCaLVChanging(value);
					this.SendPropertyChanging();
					this._MaCaLV = value;
					this.SendPropertyChanged("MaCaLV");
					this.OnMaCaLVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaViTriLV", DbType="Int")]
		public System.Nullable<int> MaViTriLV
		{
			get
			{
				return this._MaViTriLV;
			}
			set
			{
				if ((this._MaViTriLV != value))
				{
					this.OnMaViTriLVChanging(value);
					this.SendPropertyChanging();
					this._MaViTriLV = value;
					this.SendPropertyChanged("MaViTriLV");
					this.OnMaViTriLVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThuLamViec", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ThuLamViec
		{
			get
			{
				return this._ThuLamViec;
			}
			set
			{
				if ((this._ThuLamViec != value))
				{
					this.OnThuLamViecChanging(value);
					this.SendPropertyChanging();
					this._ThuLamViec = value;
					this.SendPropertyChanged("ThuLamViec");
					this.OnThuLamViecChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CaLamViec_PhanCongLamViec", Storage="_CaLamViec", ThisKey="MaCaLV", OtherKey="Id", IsForeignKey=true)]
		public CaLamViec CaLamViec
		{
			get
			{
				return this._CaLamViec.Entity;
			}
			set
			{
				CaLamViec previousValue = this._CaLamViec.Entity;
				if (((previousValue != value) 
							|| (this._CaLamViec.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CaLamViec.Entity = null;
						previousValue.PhanCongLamViecs.Remove(this);
					}
					this._CaLamViec.Entity = value;
					if ((value != null))
					{
						value.PhanCongLamViecs.Add(this);
						this._MaCaLV = value.Id;
					}
					else
					{
						this._MaCaLV = default(int);
					}
					this.SendPropertyChanged("CaLamViec");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_PhanCongLamViec", Storage="_NhanVien", ThisKey="MaNV", OtherKey="Id", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.PhanCongLamViecs.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.PhanCongLamViecs.Add(this);
						this._MaNV = value.Id;
					}
					else
					{
						this._MaNV = default(int);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
