<?xml version="1.0" encoding="utf-8"?><Database Name="ScheduleManagement" Class="ScheduleManagementDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=ScheduleManagement;User ID=sa" SettingsObjectName="ScheduleManagementUsingWFA.Properties.Settings" SettingsPropertyName="ScheduleManagementConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CaLamViec" Member="CaLamViecs">
    <Type Name="CaLamViec">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Ca" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="CaLamViec_PhanCongLamViec" Member="PhanCongLamViecs" ThisKey="Id" OtherKey="MaCaLV" Type="PhanCongLamViec" />
    </Type>
  </Table>
  <Table Name="dbo.ChiTietNhanVien" Member="ChiTietNhanViens">
    <Type Name="ChiTietNhanVien">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Mau" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CaLV" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ThuLV" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="NhanVien_ChiTietNhanVien" Member="NhanVien" ThisKey="Id" OtherKey="Id" Type="NhanVien" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HoTen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ThoiGianLV" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="NhanVien_ChiTietNhanVien" Member="ChiTietNhanViens" ThisKey="Id" OtherKey="Id" Type="ChiTietNhanVien" />
      <Association Name="NhanVien_PhanCongLamViec" Member="PhanCongLamViecs" ThisKey="Id" OtherKey="MaNV" Type="PhanCongLamViec" />
    </Type>
  </Table>
  <Table Name="dbo.PhanCongLamViec" Member="PhanCongLamViecs">
    <Type Name="PhanCongLamViec">
      <Column Name="MaNV" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaCaLV" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaViTriLV" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ThuLamViec" Type="System.String" DbType="NChar(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="CaLamViec_PhanCongLamViec" Member="CaLamViec" ThisKey="MaCaLV" OtherKey="Id" Type="CaLamViec" IsForeignKey="true" />
      <Association Name="NhanVien_PhanCongLamViec" Member="NhanVien" ThisKey="MaNV" OtherKey="Id" Type="NhanVien" IsForeignKey="true" />
      <Association Name="ViTriLamViec_PhanCongLamViec" Member="ViTriLamViec" ThisKey="MaViTriLV" OtherKey="Id" Type="ViTriLamViec" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThoiGianLamViec" Member="ThoiGianLamViecs">
    <Type Name="ThoiGianLamViec">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ThoiGian" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ViTriLamViec" Member="ViTriLamViecs">
    <Type Name="ViTriLamViec">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ViTri" Type="System.String" DbType="NChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="ViTriLamViec_PhanCongLamViec" Member="PhanCongLamViecs" ThisKey="Id" OtherKey="MaViTriLV" Type="PhanCongLamViec" />
    </Type>
  </Table>
</Database>